path_file_publisher:
  ros__parameters:
    # filepath:
    # "./install/pure_pursuit/share/pure_pursuit/path_files/levine_rough_path.csv"
    filepath: ./install/pure_pursuit/share/pure_pursuit/path_files/aims_path.csv

pure_pursuit:
  ros__parameters:
    lookahead_distance_m: 1.0
    longitudinal_velocity_ms: 0.8
    max_longitudinal_velocity_ms: 1.0
    min_longitudinal_velocity_ms: 0.2
    car_frame: "ego_racecar/base_link"
    map_frame: "map"
  
car_pose_publisher:
  ros__parameters:
    source_frame: "ego_racecar/base_link"
    target_frame: "map"

laser_costmap:
  ros__parameters:
    height_c: 100
    width_c: 75
    resolution_m_c: 0.05
    splat_radius: 4

rrt:
  ros__parameters:
    path_frame: "map"
    goal_radius_m: 0.20
    new_point_distance_m: 0.25
    max_rrt_iterations: 200